### ISSUE TITLE
new idea and congratulations

### ISSUE THREAD

**Issue by federicopenin** [gljubojevic/tactics-board#6]
Firstly I would love to ask you a question, You are Goran Ljubojević the player of soccer?
I have a new little idea,  i would like to change the picture of background to support more games (Basket or Hockey). Is a better way for  increase of people of destination of our product

**Comment by gljubojevic** [comment]
To answer first question... No I'm not soccer player only share name with famous soccer player.

About backgrounds...
Background is not only background image it is SVG vector scaled futsal pitch with real dimensions in "cm" so everything on pitch can be to scale as on real pitch. Goal for this was to have exact proportions of pitch to make it more "real".
Here you can see how is defined:
https://github.com/gljubojevic/tactics-board/blob/57a4f8278ca2356d993314d2c5fd966560a5cc77/src/editors/PitchEdit.js#L496

Adding other types of pitch (Basket, Hockey..) is possible but currently requires a lot of work. Original idea was to enable switching different types of pitch but before even trying I would like to finish what is currently started.
- Adding optional elements
- Animation playback of tactics key frames (currently only shows timeline and controls)
- Saving tactics permanently e.g. google firebase
- Sharing tactics and collaboration in tactics creation

Unfortunately all of this is being done in my spare time and you can see that progress is slow, however if you are willing to participate in project we can talk about it because I would need to explain how project is setup and how you can do pull requests. So let me know ...
